language: node_js
sudo: false

cache:
  - npm

node_js:
  - "9"

before_script:
  - npm install gitbook-cli -g
  - gitbook fetch latest
  - gitbook install

script:
  - cd ./ && gitbook build

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: ./_book
    keep-history: false
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: ./book.pdf
    skip_cleanup: true
    overwrite: true
